global:
  message: Welcome to Customer Service Dev Environment!!
server:
  port: 8081
message: Hellom From Dev!
spring:
  datasource:
	url: jdbc:mysql://localhost:3306/customer_master
	username: root
	password: Root@2026
  jpa:
	hibernate:
	  ddl-auto: update
	show-sql: false
